---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
